[package]
name = "serde-format-example"
version = "0.1.0"
authors = ["Mark McCaskey <maoeurk@wasmer.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
